feat(TUP-29701): upgrade eclipse (#3966)
* feat(TUP-29701): upgrade eclipse

* change assert

* fix assert issue

* fix compilation error

* change StringMatcher

* change to apache StringUtils because split function was removed from
eclipse one

* change manifest

* TUP-29701 modify pom to fix NoClassDefFoundError:
com/sun/jna/platform/win32/VersionHelpers

* TUP-29701  change pom for jna

* TUP-29701 try add javax.inject to require bundle

* TUP-29701 try add javax.inject to manifest

* TUP-29701 fix missing required class when start studio

* TUP-29701 change to public

* TUP-31484 fix xerces issue

* TUP-31484 add plugins to features to make it exist in license

* try change version to force use 1.68.0
org.bouncycastle.bcprov 1.68.0